#!/usr/bin/env python3
"""Generate ``b1k_object_names.py`` from the BEHAVIOR-1K annotations.

BEHAVIOR-1K object ids come in three shapes that a regex cannot tell apart:

    floors                      bare category
    coffee_table_koagbh_0       <category>_<6-letter model hash>_<scene index>
    allen_wrench_189            <category>_<global instance number>

``coffee_table_koagbh_0`` and ``allen_wrench_189`` are structurally identical
(``<words>_<6 letters>_<digits>`` vs ``<words>_<6 letters>_<digits>``), so
stripping a trailing 6-letter token as if it were always a hash turns
"allen wrench" into "allen" and "swiss cheese" into "swiss".

The vocabulary is closed (573 ids -> 281 categories), so the fix is a
hand-audited whitelist of 6-letter tokens that are real words, not hashes.
Re-run this script if the dataset gains new objects; audit any additions it
reports before committing.

Usage:
    python scripts/b1k_build_object_names.py <b1k_root> [-o <out.py>]
"""

from __future__ import annotations

import argparse
import collections
import glob
import json
import os
import re
import sys

# 6-letter tokens that are genuine words in a category name, not model hashes.
# Audited against the full 573-id vocabulary; see the module docstring.
REAL_WORD_SUFFIXES = frozenset(
    {
        "basket",
        "bottle",
        "camera",
        "candle",
        "cheese",
        "coffee",
        "cookie",
        "filter",
        "gloves",
        "kettle",
        "pepper",
        "puzzle",
        "racket",
        "tomato",
        "tripod",
        "wrench",
    }
)

# Tokens that appear inside object_id lists but denote a hand or the robot
# itself rather than a scene object.
PSEUDO_OBJECTS = frozenset({"left", "right", "robot"})

_TRAILING_NUMS = re.compile(r"(?:_\d+)+$")
_HASH_AND_NUMS = re.compile(r"_([a-z]{6})(?:_\d+)+$")


def normalize_raw(obj_id: str) -> str:
    """Turn a raw object id into a display name. Pure function, no lookups."""
    s = obj_id.strip().replace("-", "_")
    # "diced__chili" -> "diced_chili"
    s = re.sub(r"_{2,}", "_", s)

    m = _HASH_AND_NUMS.search(s)
    if m and m.group(1) not in REAL_WORD_SUFFIXES:
        s = s[: m.start()]
    else:
        s = _TRAILING_NUMS.sub("", s)

    return re.sub(r"\s+", " ", s.replace("_", " ")).strip()


def collect_object_ids(root: str) -> collections.Counter:
    def flat(x):
        if isinstance(x, list):
            for y in x:
                yield from flat(y)
        elif x is not None:
            yield x

    counts: collections.Counter = collections.Counter()
    files = sorted(glob.glob(os.path.join(root, "annotations/task-*/episode_*.json")))
    if not files:
        raise SystemExit(f"no annotations found under {root}/annotations/task-*/")
    for path in files:
        with open(path) as f:
            ann = json.load(f)
        for skill in ann.get("skill_annotation") or []:
            for group in skill.get("object_id") or []:
                for obj in flat(group):
                    counts[obj] += 1
    print(f"scanned {len(files)} annotation files, {len(counts)} unique object ids")
    return counts


def render_module(counts: collections.Counter) -> str:
    mapping = {obj: normalize_raw(obj) for obj in sorted(counts)}

    by_category: dict[str, list[str]] = collections.defaultdict(list)
    for obj, name in mapping.items():
        by_category[name].append(obj)

    lines = [
        '"""Object id -> display name for BEHAVIOR-1K.',
        "",
        "GENERATED by scripts/b1k_build_object_names.py -- do not edit by hand.",
        "The mapping is hand-audited; regenerate and re-audit when the dataset changes.",
        '"""',
        "",
        "# Tokens that denote a hand or the robot, not a scene object.",
        "PSEUDO_OBJECTS = frozenset(" + repr(sorted(PSEUDO_OBJECTS)) + ")",
        "",
        f"# {len(mapping)} object ids -> {len(by_category)} categories",
        "OBJECT_NAME_MAP = {",
    ]
    for obj, name in mapping.items():
        lines.append(f"    {obj!r}: {name!r},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines), mapping, by_category


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root", help="BEHAVIOR-1K dataset root")
    ap.add_argument(
        "-o",
        "--out",
        default="dataset_upload/dataset_loaders/b1k_object_names.py",
    )
    args = ap.parse_args()

    counts = collect_object_ids(args.root)
    source, mapping, by_category = render_module(counts)

    with open(args.out, "w") as f:
        f.write(source)
    print(f"wrote {args.out}: {len(mapping)} ids -> {len(by_category)} categories")

    # Audit aids: anything a human should look at before committing.
    suspicious = [
        (name, ids)
        for name, ids in sorted(by_category.items())
        if len(name) < 3 or re.search(r"\d", name) or "  " in name
    ]
    if suspicious:
        print("\n⚠️  suspicious categories (audit these):")
        for name, ids in suspicious:
            print(f"    {name!r} <- {ids[:3]}")

    stripped_words = sorted(
        {
            m.group(1)
            for obj in mapping
            if (m := _HASH_AND_NUMS.search(obj.replace("-", "_")))
            and m.group(1) not in REAL_WORD_SUFFIXES
        }
    )
    print(f"\n6-letter tokens treated as model hashes ({len(stripped_words)}):")
    print("   ", " ".join(stripped_words))
    print("\nIf any of the above is a real English word, add it to REAL_WORD_SUFFIXES and rerun.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
